// This file was generated by Dashcode from Apple Inc.
// DO NOT EDIT - This file is maintained automatically by Dashcode.
function setupParts() {
    if (setupParts.called) return;
    setupParts.called = true;
    CreateGlassButton('done', { text: 'Done', onclick: 'showFront' });
    CreateShape('timer-bg', { rightImageWidth: 18, leftImageWidth: 18 });
    CreateText('event-label', { text: 'Event Label' });
    CreateText('Rank_desc', { text: unescape('%u0392%u03B1%u03B8%u03BC%u03CC%u03C2') });
    CreateText('Division_desc', { text: unescape('%u03A3%u03CE%u03BC%u03B1/%u038C%u03C0%u03BB%u03BF') });
    CreateText('Name_desc', { text: unescape('%u039F%u03BD%u03BF%u03BC%u03B1%u03C4%u03B5%u03C0%u03CE%u03BD%u03C5%u03BC%u03BF') });
    CreateText('Date_desc', { text: unescape('%u0397%u03BC%u03B5%u03C1%u03BF%u03BC%u03B7%u03BD%u03AF%u03B1 %u03BA%u03B1%u03C4%u03AC%u03C4%u03B1%u03BE%u03B7%u03C2:') });
    CreateText('Prison_desc', { text: unescape('%u03A6%u03C5%u03BB%u03B1%u03BA%u03AE:') });
    CreateText('Date_fire', {  });
    CreateText('Full_Name', {  });
    CreateText('label-days', { text: 'DAYS' });
    CreateInfoButton('info', { foregroundStyle: 'white', frontID: 'front', onclick: 'showBack', backgroundStyle: 'black' });
    CreateText('url', { text: 'http://www.macgiorgosgr.com' });
    CreateText('e-mail', { text: 'e-mail:' });
    CreateText('e-mail_addr', { text: 'macgiorgosgr@macgiorgosgr.com' });
}
window.addEventListener('load', setupParts, false);
